gpstrip/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from account import views
from .forms import (UserLoginForm,  PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),

]

gpstrip/cart/urls.py
from django.urls import path

from cart import views
from cart.views import add_to_cart, remove_from_cart, update_cart
#
# app_name = 'cart'

urlpatterns = [
    path('cart2/', views.cart_summary, name='cart_summary'),
    path('add-to-cart/<slug:item_slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:item_slug>/', remove_from_cart, name='remove-from-cart'),
    path('update-cart/<slug:item_slug>/', update_cart, name='update-cart'),
]

gpstrip/gpstrace/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('', include('cart.urls')),
    path('', include('newsletter.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('feedback.urls')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r'^__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpstrip/store/urls.py
from django.urls import path

from . views import *




urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('item/<slug:item_slug>/', ShowItem.as_view(), name='itemv'),
    path('category/<slug:cat_slug>/', CategoryTracker.as_view(), name='category'),
    path('checkout', CheckOutView.as_view(), name='checkout'),
    path('index', HomeView.as_view(), name='index'),
    path('cart', CartView.as_view(), name='cart'),
    path('logout/', logout_user, name='logout'),
    path('add-to-favorite/<slug:item_slug>/', add_to_favorite, name='add-to-favorite'),
    path('remove-from-favorite/<slug:item_slug>/', remove_from_favorite, name='remove-from-favorite'),
    path('search', Search.as_view(), name='search'),
    path('about/', About.as_view(), name='about'),
    path('favorite/', ShowFavorite.as_view(), name='favorite'),
    path('delivery/', delivery, name='delivery'),
    path('payment/', payment, name='payment'),
    path('return_terms/', return_terms, name='return_terms'),
    path('contacts/', contacts, name='contacts'),
    path('city-json/', get_json_car_data, name='city-json'), # шлях запуску функції вюшки для виводу міст у випадаючому переліку checkout.html
    path('address-json/<str:city>/', get_json_address_data, name='address-json'), # шлях запуску функції вюшки для отримання переліку вулиць необхідного міста у випадаючому переліку checkout.html
    path('np_api/', np_api, name='np_api'), # шлях запуску функції вюшки для отримання переліку міст нової пошти
    path('np_api_list/', np_api_list, name='np_api_list'), # шлях запуску функції вюшки для отримання переліку міст нової пошти
    path('main/<slug:number>/', cv_feedback, name='cv_feedback')
    ]

gpstrip/cart/models.py
from django.db import models

# Create your models here.

gpstrip/store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

LABEL_CHOICES = (
    ('Новинка', 'Новинка'),
    ('Популярне', 'Популярне'),
)

ONE_HUNDRED = 1000
FIVE_HUNDRED = 5000
TEN_HUNDRED = 10000
TWENTY_HUNDRED = 20000


BATTERY_CHOICES = (
    (ONE_HUNDRED, 1000),
    (FIVE_HUNDRED, 5000),
    (TEN_HUNDRED, 10000),
    (TWENTY_HUNDRED, 20000),

)

class Item(models.Model):
    title = models.CharField(max_length=100, null=True, verbose_name='Назва товару')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, null=True)
    photo = models.ImageField(upload_to='img', null=True)
    price = models.FloatField(blank=True, null=True, verbose_name='Ціна товару')
    discount = models.IntegerField(blank=True, null=True, verbose_name='Знижка у %')
    short_description = models.TextField(max_length=5000, null=True, blank=True, verbose_name='Короткий опис')
    description = models.TextField(max_length=5000, null=True, blank=True, verbose_name='Опис')
    details = models.TextField(max_length=5000, null=True, blank=True, verbose_name='Деталі')
    label = models.CharField(choices=LABEL_CHOICES, max_length=20, null=True, blank=True, verbose_name='Акційна мітка')
    battery = models.IntegerField(choices=BATTERY_CHOICES, null=True, blank=True,
                               verbose_name='Ємність акумуляторної батареї')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('itemv', kwargs={'item_slug': self.slug})

    def discount_price_calculation(self):
        self.discount_price = self.price - (self.price * (self.discount / 100))
        return self.discount_price

    def discount_save_calculation(self):
        self.discount_save = self.price - self.discount_price
        return self.discount_save

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={'item_slug': self.slug})

    def get_add_to_favorite_url(self):
        return reverse('add-to-favorite', kwargs={'item_slug': self.slug})

    def get_update_cart_url(self):
        return reverse('update-cart', kwargs={'item_slug': self.slug})


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery')
    Item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='images')


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категорія')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL', null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        if self.item.discount:
            return self.quantity * (self.item.price - (self.item.price * (self.item.discount / 100)))
        else:
            return self.quantity * self.item.price

    # def get_total_order_price(self):
    #     return self.get_total_item_price()

    def get_final_price(self):

        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(null=True)
    first_name = models.CharField(max_length=200,  blank=True, null=True)
    last_name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    street_address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    index = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    first_name_np = models.CharField(max_length=200, blank=True, null=True)
    last_name_np = models.CharField(max_length=200, null=True)
    phone_np = models.CharField(max_length=200, null=True)
    city_np = models.CharField(max_length=200, null=True)
    address_np = models.CharField(max_length=200, null=True)
    order_notes = models.TextField(max_length=5000, null=True, blank=True)
    order_total = models.CharField(max_length=20, null=True, blank=True)



    def __str__(self):
        return self.user.user_name
    def ordered_item_list(self, slug):
        item_order = Order.objects.filter(user=self.user)
        if 'TK905' in 'TK905':
            return True

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

class City(models.Model):
    ref = models.CharField(max_length=100)
    name = models.CharField(max_length=20)

    def __str__(self):
        return (str(self.name))


class Favorite(models.Model):
    item_favorite = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.item_favorite.slug

gpstrip/store/forms.py
from django import forms
from .models import Order
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CheckoutForms(forms.Form):
    first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': "Ім'я", 'class': "input"
    }))
    last_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Прізвище', 'class': "input"
    }))
    street_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Вулиця', 'class': "input"
    }))
    city = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Місто', 'class': "input"
    }))
    email = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Електронна адреса', 'class': "input"
    }))
    index = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': ' Індекс', 'class': "input"
    }))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Телефон', 'class': "input"
    }))
    city_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Телефон', 'class': "input"
    }))
    first_name_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': "Ім'я", 'class': "input"
    }))
    last_name_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Прізвище', 'class': "input"
    }))
    address_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Вулиця', 'class': "input"
    }))
    phone_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Телефон', 'class': "input"
    }))
    city_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Місто', 'class': "input"
    }))
    address_np = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Відділення Нової Пошти', 'class': "input"
    }))
    order_notes = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Нотатки до замовлення', 'class': "input"
    }))

class FeedbackForms(forms.Form):
    feedback_text = forms.CharField(label="Відгук", required=False, widget=forms.Textarea(attrs={
        'placeholder': 'Відгук'}))

gpstrip/cart/views.py
from audioop import reverse

from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from store.models import Item, OrderItem, Order
from django.utils import timezone
from django.http import HttpResponseRedirect

def cart_summary(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})


# Create your views here.
def add_to_cart(request, item_slug):
    if request.user.is_authenticated:
        try:
            order_qty = request.GET["order-qty"]
        except:
            order_qty = 1
        item = get_object_or_404(Item, slug=item_slug)
        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            user=request.user,
            ordered=False
        )
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item.quantity += int(order_qty)
                order_item.save()
                messages.info(request, "Кількість товару в корзині збільшена")
                return redirect(request.META.get('HTTP_REFERER'))
            else:
                order.items.add(order_item)
                order_item.quantity = int(order_qty)
                order_item.save()
                messages.info(request, "Товар добавлено до корзини")
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            ordered_date = timezone.now()
            order = Order.objects.create(
                user=request.user, ordered_date=ordered_date)
            order.items.add(order_item)
            order_item.quantity = int(order_qty)
            order_item.save()
            messages.info(request, "Товар добавлено до корзини")
            return redirect(request.META.get('HTTP_REFERER'))

    else:
        cart = Cart(request)
        try:
            order_qty = int(request.GET["order-qty"])
        except:
            order_qty = 1
        item = get_object_or_404(Item, slug=item_slug)
        cart.add(item=item, qty=order_qty)
        return redirect(request.META.get('HTTP_REFERER'))


def remove_from_cart(request, item_slug):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, slug=item_slug)
        order_qs = Order.objects.filter(
            user=request.user,
            ordered=False
        )
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item = OrderItem.objects.filter(
                    item=item,
                    user=request.user,
                    ordered=False
                )[0]
                order.items.remove(order_item)
                order_item.delete()
                messages.info(request, "Товар було видалено з корзини")
                return redirect(request.META.get('HTTP_REFERER'))
            else:
                messages.info(request, "Товар відсутній в корзині")
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.info(request, "У вас не має активних замовлень")
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        cart = Cart(request)
        item = get_object_or_404(Item, slug=item_slug)
        cart.delete(item=item)
        return redirect(request.META.get('HTTP_REFERER'))

def update_cart(request, item_slug):
    order_qty = request.GET["order-qty"]
    item = get_object_or_404(Item, slug=item_slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_item.quantity = int(order_qty)
    order_item.save()
    messages.info(request, "Кількість товару в корзині змінена")
    redirect("cart")
    return redirect("cart")

gpstrip/store/templates/store/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GPSTrip-Про нас</title>
    	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Electro - HTML Ecommerce Template</title>

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>

<body>
{% include "store/navbar.html" %}
<div class="container-fluid">
<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-10">
<br>
						<p>
    В нашому інтернет магазині представлені якісні та надійні GPS трекера, які були відібрані протягом 7 років роботи нашого магазину. На прилавку залишились тільки ті GPS трекера, які відрізняються надійністю роботи, мінімум браку в партії та відсутністю скарг з боку замовників. </p>

<p> Всі трекера поставляються вже налаштовані і у Вас не виникне жодних проблем із запуском пристрою. А якщо і запитання виникнуть, дзвоніть, пишіть в будь-який, чи то робочий, чи не робочий час, і ми оперативно дамо відповідь та вирішимо проблему із роботою трекера віддаллено.</p>
			<p> Ми надаємо по життєву технічну підтримку наших трекерів. Та не вагайтесь подзвонити нам, якщо у Вас виникнуть запитання перед покупкою.

	7 річний досвід роботи з GPS трекерами зробив нас спеціалістами в даній сфері. </p>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
</div>


</body>
{% include "store/footer.html" %}
</body>

<script src="{% static '/js/slick.min.js' %}"></script>
<script src="{% static '/js/nouislider.min.js' %}"></script>
<script src="{% static '/js/jquery.zoom.min.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>
<script src="{% static '/js/checkbox.js' %}"></script>
</html>

gpstrip/store/templates/store/contacts.html
{% load static %}
{% include "store/navbar.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>GPSTrip-Контакти</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

<body>
<br>
<div class="container" style="max-width: 1000px">
    <div class="col-12">

        <ul>
            <li><a href="#"><i class="fa fa-phone"></i> +38(096)1864719</a></li>
            <li><a href="#"><i class="fa fa-envelope-o"></i> andriyav@gmail.com</a></li>
            <li><a href="#"><i class="fa fa-map-marker"></i> Львів</a></li>
        </ul>


    </div>
</div>
</body>
{% include "store/footer.html" %}
</body>
</html>

gpstrip/store/templates/store/footer.html
   {% load static %}
{% load store_tags %}
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="newsletter">
                        <p>Підписатись на <strong>НОВИНИ</strong></p>
                        <form method="POST" action="{% url 'news-letter' %}">
                            {% csrf_token %}
                            <input class="input" name="subscriber" type="email" placeholder="Email">
                       <button class="newsletter-btn"><i class="fa fa-envelope"></i> Підписатись</button>
                        </form>
                        <ul class="newsletter-follow">
<!--                            <li>-->
<!--                                <a href="#"><i class="fa fa-facebook"></i></a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#"><i class="fa fa-twitter"></i></a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#"><i class="fa fa-instagram"></i></a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#"><i class="fa fa-pinterest"></i></a>-->
<!--                            </li>-->
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
<!--     /NEWSLETTER-->
<!--     FOOTER-->
    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Про нас</h3>
                            <h3>GPStrace</h3>
                            <ul class="footer-links">
                                <li><a href="#"><i class="fa fa-map-marker"></i>Львів</a></li>
                                <li><a href="#"><i class="fa fa-phone"></i>+38(096)1864719</a></li>
                                <li><a href="#"><i class="fa fa-envelope-o"></i>andriyav@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Категорії</h3>
                            <ul class="footer-links">
                                <li>{% get_categories %}</li>
<!--                                <li><a href="#">Hot deals</a></li>-->
<!--                                <li><a href="#">Laptops</a></li>-->
<!--                                <li><a href="#">Smartphones</a></li>-->
<!--                                <li><a href="#">Cameras</a></li>-->
<!--                                <li><a href="#">Accessories</a></li>-->
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix visible-xs"></div>
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Інформація</h3>
                            <ul class="footer-links">
                                <li><a href="{% url 'about' %}">Про нас</a></li>
                                <li><a href="{% url 'contacts' %}">Контакти</a></li>
                                <li><a href="{% url 'delivery' %}">Доставка</a></li>
                                <li><a href="{% url 'payment' %}">Оплата</a></li>
                                <li><a href="{% url 'return_terms' %}">Умови повернення</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Сервіси</h3>
                            <ul class="footer-links">
                                <li><a href="{% url "account:login" %}">Обліковий запис</a></li>
                                <li><a href="{% url 'cart' %}">Корзина</a></li>
<!--                                <li><a href="#">Відмічене</a></li>-->
<!--                                <li><a href="#">Track My Order</a></li>-->
<!--                                <li><a href="#">Help</a></li>-->
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->
        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">
                        <ul class="footer-payments">
                            <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                            <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                        </ul>
                        <span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i
                                class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                    target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->

gpstrip/store/templates/store/list_categories.html
{% load static %}

<ul>
    {% for c in cats %}
    <div><br></div>
    <li><a href="{{c.get_absolute_url}}">{{c.name}}</a></li>
    {% endfor %}

</ul>